### ISSUE TITLE
Use BLT_CXX_STANDARD rather than custom logic

### ISSUE THREAD

**Issue by adayton1** [LLNL/RAJA#1009]
Is it possible to use BLT_CXX_STANDARD rather than the custom logic for adding the -std=c++11/14/17 flag? I would set RAJA_CXX_STANDARD_FLAG to -std=c++11/14/17 if I knew that flag was portable across all compilers, but I haven't found anything that says that flag is portable.

Also, the default value of "default" is kind of confusing when trying to explain this flag to others.

**Comment by trws** [comment]
We certainly could switch, when we make the change to default to C++14 it might be more reasonable too.  The reason for the flag being the way it is comes from two issues.  Historically the cmake support for finding the right option for that for HPC compilers was poor, and the selection code was written before BLT happened, so it's partly just historical.  The other is that RAJA produces substantially better code if you let it use C++14, or especially C++17, in some cases, so the older behavior of "give me the highest thing this compiler can be seen to support" has some benefits.

I suppose if the user is setting the standard that way we probably want to override that anyway, will try to make some time to look into this.

**Comment by adayton1** [comment]
It would be nice to be able to easily set the standard since I would imagine all the benefits you are talking about would occur if the host code is compiled with c++14 or c++17 (since most of RAJA is header based). Only two or three files are actually compiled in the RAJA project.

**Comment by brandonneth** [comment]
I was able to change the -std=* flag using the BLT variable BLT_CXX_STD, rather than BLT_CXX_STANDARD. By adding -DBLT_CXX_STD="c++14" to a project's cmake call, it changed the -std=* flag for both RAJA source files and the project's source files. 

It may be a good idea for us to add some sort of support for BLT_CXX_STANDARD as a variable, as I can't find an example of cmake using "STD" over "STANDARD" in a variable name.
