### ISSUE TITLE
RAJA does not respect my wish to not use an external CUB

### ISSUE THREAD

**Issue by mclarsen** [LLNL/RAJA#1194]
https://github.com/LLNL/RAJA/blob/4a07809dfd0d8dcd4daf5eeb91fb692394c5815b/cmake/SetupPackages.cmake#L32

I don't want to use an external cub, but  no matter what I do, RAJA always uses the system install. I can't figure out if its even possible to use the submodule if there is a the is findable by `FindPackage`. Any advice?

**Comment by mclarsen** [comment]
Yes. The issue is the `OR` in this statement. Here is the relevant code:

```
if (RAJA_ENABLE_CUDA OR RAJA_ENABLE_EXTERNAL_CUB)
  find_package(CUB)
  if (CUB_FOUND)
    set(RAJA_ENABLE_EXTERNAL_CUB On)
```
So if CUDA is enabled (which it has to be), it doesn't matter what the human wants, this code will always set `RAJA_ENABLE_EXTERNAL_CUB` to `ON`.

**Comment by rhornung67** [comment]
I agree that CMake logic looks strange. Let me poke some people who may know better than me about how this is supposed to work.

**Comment by MrBurmark** [comment]
Figuring out what cub to use is a bit weird. The user can specify to use an external cub by setting the flag and setting cub_dir. Otherwise the version of cub used depends on the cuda version, newer versions of cuda that have their own cub install in the cuda toolkit which is found by find_package, while older versions of cuda use the raja cub submodule.
So the logic is trying to differentiate those cases, but not really doing the right thing in all cases. The failure of find_package is used here as a flag to use the cub submodule in RAJA with older cuda versions. The logic should be changed as you suggested with an else clause that handles "non-external" cub by keying off of the cuda version directly to decide if it should use the cub in the cuda toolkit or the raja cub submodule.

**Comment by mclarsen** [comment]
My main point is that if I am given a cmake option, then there should not be a path to use a CUB i don't want. If want to use an external cub, it should never fall back to the submodule (error if an appropriate external one can
t be found). If I want to use the submodule, then never go out and find a system install.

**Comment by MrBurmark** [comment]
@mclarsen Can you take a look at #1201 to see if it fixes this issue?

**Comment by mclarsen** [comment]
I missed this. I think I get too many git emails. I am using cuda 11.5 and don't want to use an external cub for complicated reasons, so the forcing the use of an external cub, which overrides the cmake option, doesn't work for me.
