### ISSUE TITLE
Could the sequential atomic methods take a non volatile pointer?

### ISSUE THREAD

**Issue by corbett5** [LLNL/RAJA#703]
TLDR: I'd like `RAJA::atomicAdd< RAJA::seq_atomic >` to work with a `std::string`.

Currently the sequential atomic methods such as `atomicAdd` take a volatile pointer
```c++
T atomicAdd(seq_atomic, T volatile *acc, T value)
```
I'm writing a general purpose container similar to the following
```c++
template< typename T >
struct Container
{
  template< typename Policy=RAJA::seq_atomic >
  void add( int position, T const & value )
  {
    RAJA::atomicAdd< Policy >( m_data + position, value );
  }

  T * m_data;
}
```
But the use of `atomicAdd` limits the container to only holding types for which T can be copy constructed from a volatile value, even if `Container< T >::add` is never instantiated with a non-sequential atomic policy.

It seems to me that the sequential atomic methods such as `atomicAdd` should have a signature of 
```c++
T atomicAdd(seq_atomic, T * acc, T value)
```
or better yet to eliminate a copy
```c++
T atomicAdd(seq_atomic, T * acc, T const & value)
```

**Comment by MrBurmark** [comment]
@corbett5 has this been resolved?

**Comment by corbett5** [comment]
I've worked around it, but if you'd like I can address those comments on #704 if you think that should go in.

**Comment by MrBurmark** [comment]
Thanks for offering, there's a lot of good changes in that PR, but we're going to switch to the atomics in desul sometime soon. Desul (https://github.com/desul/desul) is a collab with some other folks, namely the Kokkos folks to have some shared utilites like atomics. The desul atomics support more things like memory orders and scoping (like system vs device vs block scope in cuda). So I think we'll close the PR since desul is coming soon.

**Comment by corbett5** [comment]
Sounds good to me.
