### ISSUE TITLE
add version check for cuda, maybe also hip etc, in cmake

### ISSUE THREAD

**Issue by trws** [LLNL/RAJA#947]
Our build failure with a version of cuda that's outside our supported range currently prints a big mess of errors that don't point to the cause very well.   It would be good to add some logic to catch it and print a more meaningful error.

**Comment by brandonneth** [comment]
CUDA arch level minimum: sm_35
Googletest v0.11.0 or newer requires CUDA v9.2.x or newer
RAJA requires rocm v3.5 or newer

**Comment by brandonneth** [comment]
**CUDA Arch** 
CUDA arch level check is in there already.

**CUDA Version**
CUDA_VERSION_STRING is the cmake variable, and is set when BLT is setup on line 157 of CMakeLists.txt.

Added check for CUDA versions less that 9.2 and error out for those versions. (wrapped to check for ENABLE_CUDA)

**rocm/hip**
BLT does not set a rocm version number, but does set a hip version number. I assume this is the version number that should be checked here. I added a similar check for the HIP version number.

I can only half-test this check, because I don't have access to a system with a new enough version of hip.
